### ISSUE TITLE
Can't override shariff SPQR extensions

### ISSUE THREAD

**Issue by humantex** [SPQRInc/pagekit-assets#1]
I can create the CSS to override shariff-buttons, but can never get it to apply. 'Assets' doesn't insert either the style block or css file link that it creates at the absolute end of the linked references... trying it with border-radius as a test, i.e.:

```
 <link href="/packages/friendlyit/search/assets/css/searchwidget.css?v=748a" rel="stylesheet">
        <style>shariff-button a {
border-radius: 10px 10px 10px 10px;
-moz-border-radius: 10px 10px 10px 10px;
-webkit-border-radius: 10px 10px 10px 10px;
}</style>
        <link href="/packages/spqr/shariff/app/assets/shariff/build/shariff.complete.css?v=748a" rel="stylesheet">
```
or

```
        <link href="/packages/spqr/assets/assets/custom/shariff-override.css?v=748a" rel="stylesheet">
        <link href="/packages/spqr/shariff/app/assets/shariff/build/shariff.complete.css?v=748a" rel="stylesheet">
        <script>var $pagekit = {"url":"","csrf":"618f0f4cb8ac20f68e0d7ef465cf958857f6a45d"};</script>
```

I don't know if the same thing happens with any of your other extensions, since I'm only using these 2 at the moment.

**Comment by ahoiroman** [comment]
Hi,

Did you choose the nodes where the assets should be inserted?

**Comment by ahoiroman** [comment]
I created a little demo screencast on how to use JS/CSS and node selection:

![2017-11-15 08 03 14](https://user-images.githubusercontent.com/23051150/32823289-e29c9baa-c9dc-11e7-83eb-79a7e5798737.gif)

I also tried to override the shariff-styling:

![bildschirmfoto 2017-11-15 um 08 12 48](https://user-images.githubusercontent.com/23051150/32823301-f3b99280-c9dc-11e7-8b59-9f94729b1eb1.png)
![bildschirmfoto 2017-11-15 um 08 12 55](https://user-images.githubusercontent.com/23051150/32823302-f3d755d6-c9dc-11e7-895c-010f44980651.png)

**Comment by humantex** [comment]
I have visibility set for 'all pages'. I'm posting some cropped screen-grabs to show the settings page for the widget and asset, and one is a view page source for the site.

On the widget setup... on the settings tab is just the name (labeled, Share), set to enabled, and loaded in the 'footer' section of the theme. None of the 'overwrites' are ticked. Visibility tab is set for 'all pages'. The theme tab is:

![spqr-assets-settings-3](https://user-images.githubusercontent.com/16087649/32833890-738635a4-c9ce-11e7-929b-f6f412b1e96b.jpg)

For the asset... Visibility is also 'all pages' - w/ the settings tab as:

![spqr-assets-settings](https://user-images.githubusercontent.com/16087649/32833888-7324a0be-c9ce-11e7-8ab2-35390e030dcf.jpg)

And the view source for the site...

![spqr-assets-settings-2](https://user-images.githubusercontent.com/16087649/32833889-733a74e8-c9ce-11e7-9602-a3c6692e48c9.jpg)

Here's the site link with everything still in place if you want to see how it renders... https://enami.lumiworx.com

Shariff is loaded below everything else within the footer section of the widget list, and in the visual order it appears on the page. The CSS 'link href' from Assets never gets inserted below the line for Sheriff, and I've tried it as both an inline setting and save-as-file. The result is the same... it's always next-to-last in the header order of references, and always above Sheriff... so obviously if it's not below it, it will never override it.

If it matters, I've cloned the Avion theme from pagekit.com, and customized the css to suit my own taste.

**Comment by ahoiroman** [comment]
Hm... I don't get your point. It's not a bug of this extension, as I can not change the order of `style` or `scripts` using the helper Pagekit provides.

As you see, your content **is** being inserted inline:

```
<style>shariff-button a {
border-radius: 10px 10px 10px 10px;
-moz-border-radius: 10px 10px 10px 10px;
-webkit-border-radius: 10px 10px 10px 10px;
}</style>
```

So what you can do: Overwrite it with `!important`, if necessary, as I've shown in my screenshot.

There's also an error I guess. It has to be `.shariff-button a` - you just wrote `shariff-button a`.

![bildschirmfoto 2017-11-15 um 13 35 34](https://user-images.githubusercontent.com/23051150/32836408-f7c28cce-ca09-11e7-8d55-b0c2a7123e7a.png)
![bildschirmfoto 2017-11-15 um 13 35 26](https://user-images.githubusercontent.com/23051150/32836411-fc9c572a-ca09-11e7-892a-c983559dc5ef.png)

**Comment by ahoiroman** [comment]
I am going to close this issue, as there is no bug in spqr/assets. If you need more help using the extension or with css, please use https://pagekit-forum.org .

If you are sure that this is a bug, please reopen.
