### ISSUE TITLE
Load dependency for script

### ISSUE THREAD

**Issue by IamSAB** [SPQRInc/pagekit-assets#2]
I got an assets, javascript, which uses jquery. Now the problem is, that my assets is inserted before jquery (also before all other 'standard pagekit' assets).

In pagekit its very easy to add dependency via the scriptmanager/loader. Is it possible to do the same with your asset manager (via the UI)?

Thanks for your effort.

**Comment by ahoiroman** [comment]
I will add this with the next release.

**Comment by ahoiroman** [comment]
Got a release candidate. Would you like to test it?

**Comment by ahoiroman** [comment]
Tested it already. Version `1.0.1` is available in the marketplace.
