### ISSUE TITLE
Require other assets as dependency

### ISSUE THREAD

**Issue by IamSAB** [SPQRInc/pagekit-assets#3]
e.g.
I add a custom js script which requires moment.js. So I create a second assets of type 'url' which is for the cdns of moment.js which I load on the same page as my custom script.
Assets does not care about the order of adding the scripts, so it depends on which assets you created first. So if moment.js is added after my custom script, its utitility can not be used, as my script does not know about moment.

**Comment by ahoiroman** [comment]
As I am only adding dependencies that are shipped with Pagekit, I won't fix that - as far as I know, Pagekit does not allow to specify the order of all added scripts and styles.

If you think I'm wrong, feel free to reopen.

**Comment by IamSAB** [comment]
But it would be possible to add a dependency to another Assets of your extension, added earlier?

Your using the slug of the Asset as name/identifier at adding it to the asset manager. You could simply add a textfield, where you can add comma seperated slugs, which you want to require as dependency.
On view.content you just explode this string and add the array as dependency argument at adding the asset. 
Users could use pagekit preregistered assets and their custom assets added via the asset extension. If the idendifier is not know, it will just ignore it.
